<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Step   please wait</name>
   <tag></tag>
   <elementGuidId>0cd0cb01-2b1a-4489-bcfa-8c1cfc4255cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d89fbad1-96af-43a6-ab71-00494e4ca786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-register</value>
      <webElementGuid>10fb1fec-ded3-4b3b-9f0b-ef05eb37cceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1afd62d4-a9d2-4336-a91a-8636df3bc00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-create-account btn btn-block</value>
      <webElementGuid>21b8c59b-b6d8-486d-8985-646a3c91e2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next Step   please wait </value>
      <webElementGuid>c71eefc9-7213-45de-8b8c-eb1159eccbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-register&quot;)</value>
      <webElementGuid>866b96b0-21d6-4087-a362-0a2a5bea93fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-register']</value>
      <webElementGuid>86b211b6-9327-4342-b259-1638c1fca976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[7]/div[2]/button</value>
      <webElementGuid>6f1acad4-8ee8-4430-b64e-3522c1a99be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Statement'])[1]/following::button[1]</value>
      <webElementGuid>4754ae58-c799-48cc-ad22-53a010fc62be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>62216674-5b1e-4ded-a196-1aa73f047c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next Step']/parent::*</value>
      <webElementGuid>00493420-2c94-41b9-8f99-089ce8e28306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/button</value>
      <webElementGuid>4a14c329-f551-4362-b8e2-376e9c4e6da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-register' and @type = 'submit' and (text() = 'Next Step   please wait ' or . = 'Next Step   please wait ')]</value>
      <webElementGuid>acd6e69f-1522-4a12-9eb8-070ba05113d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
