<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_form-control btn-log bor_48151b</name>
   <tag></tag>
   <elementGuidId>c7b161d7-2a38-4c57-8136-e29e1f2627c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.btn-log.border-grey.int_tel_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16064499-163c-4121-9e77-c52eb92bcc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>69680d54-d252-4ad8-8fb0-4bb045c2aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn-log border-grey int_tel_input</value>
      <webElementGuid>369ab3c5-b384-4c12-8ad0-c393fddb8748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>f090e495-ab26-4b83-9dc1-455940443889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>8996a0df-d364-4d0c-b7c3-dcf712b04ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-0</value>
      <webElementGuid>209d153d-97c9-43fb-820b-b5ec30638d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>732f7988-3ae9-403a-82cd-92869e5f4e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 register-row&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control btn-log border-grey int_tel_input&quot;]</value>
      <webElementGuid>554a7acc-d606-4392-a54f-9cb62fada41d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='tel']</value>
      <webElementGuid>76296f88-803a-43e4-afb3-eb12539d38b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[5]/div[2]/div/input</value>
      <webElementGuid>1b6cfc06-e789-4fda-909d-ffdff6c9bce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>35cc8f87-4d88-47c5-b6be-35ee354ef2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = '812-345-678']</value>
      <webElementGuid>5d2be0f1-d5f3-4fdc-8777-92e7659d23ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
